Models/ApplicationContext.cs
using HW2.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace HW2.Models
{
    public class ApplicationContext : DbContext, IApplicationContext
    {
        public DbSet<Friend> Friends { get; set; } = null!;

        public ApplicationContext(DbContextOptions<ApplicationContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }

        public override int SaveChanges()
        {
            return base.SaveChanges();
        }
    }
}

Models/ErrorViewModel.cs
namespace HW2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Friend.cs
namespace HW2.Models
{
    public class Friend
    {
        public int FriendId { get; set; }

        public string FriendName { get; set; }

        public string Place { get; set; }

        public Friend()
        {
        }
    }
}

ViewModels/Friend/ChangeFriendRequest.cs
using System.ComponentModel.DataAnnotations;

namespace HW2.ViewModels.Friend
{
    public class ChangeFriendRequest
    {
        [Required]
        public int Id { get; set; }
        
        [Required]
        public string FriendName { get; set; }

        [Required]
        public string Place { get; set; }
    }
}

ViewModels/Friend/CreateFriendRequest.cs
using System.ComponentModel.DataAnnotations;

namespace HW2.ViewModels.Friend
{
    public class CreateFriendRequest
    {
        [Required]
        public string FriendName { get; set; }

        [Required]
        public string Place { get; set; }
    }
}

Controllers/FriendController.cs
using HW2.Interfaces;
using HW2.ViewModels.Friend;
using Microsoft.AspNetCore.Mvc;

namespace HW2.Controllers
{
    public class FriendController : Controller
    {
        readonly IFriendService _friendService;

        public FriendController(IFriendService friendService)
        {
            _friendService = friendService;
        }
        
        // GET: FriendController
        public ActionResult Index()
        {
            return View(_friendService.GetFriends());
        }

        // GET: FriendController/Details/5
        public ActionResult Details(int id)
        {
            var friend = _friendService.Details(id);
            return View(friend);
        }

        // GET: FriendController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FriendController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateFriendRequest request)
        {
            try
            {
                _friendService.CreateFriend(request);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FriendController/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        // POST: FriendController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ChangeFriendRequest request)
        {
            try
            {
                _friendService.EditFriend(request);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FriendController/Delete/5
        public ActionResult Delete(int id)
        {
            var friend = _friendService.Details(id);

            return View(friend);
        }

        // POST: FriendController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _friendService.DeleteFriend(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs
using HW2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HW2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Friend/Create.cshtml
@model HW2.Models.Friend

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Friend</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FriendName" class="control-label"></label>
                <input asp-for="FriendName" class="form-control" />
                <span asp-validation-for="FriendName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Friend/Delete.cshtml
@model HW2.Models.Friend

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Friend</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FriendId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FriendId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FriendName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FriendName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Place)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Friend/Details.cshtml
@model HW2.Models.Friend

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Friend</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FriendId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FriendId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FriendName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FriendName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Place)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FriendId }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Friend/Edit.cshtml
@model HW2.Models.Friend

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Friend</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FriendName" class="control-label"></label>
                <input asp-for="FriendName" class="form-control" />
                <span asp-validation-for="FriendName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Friend/Index.cshtml
@model IEnumerable<HW2.Models.Friend>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FriendId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FriendName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FriendId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FriendName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Place)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.FriendId }) |
                @Html.ActionLink("Details", "Details", new { id=item.FriendId }) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.FriendId  })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="container">
    <a asp-area="" asp-controller="Friend" asp-action="Index">Friend List</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HW2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HW2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HW2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HW2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>